theme: jekyll-theme-midnight
title: Práctica 7 - Digitalizando la colección de música de los abuelos
description: Se llevará a cabo un diseño orientado a objetos del modelo de datos de un sistema de información que permita almacenar una biblioteca de música.
